---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: INFO
- type: document
  path: data/theme.json
  label: Main site info
- type: document
  path: data/contacts.json
  label: Contacts
- type: heading
  label: CONTENT
- type: directory
  path: pages
  label: Pages
  create: all
  match: "**/*.md"
  templates:
  - page
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  instant_preview_command: vuepress dev -p 8080 -h 0.0.0.0
