---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: GLOBAL
- type: document
  path: data/main.json
  label: Main
- type: heading
  label: PAGE SECTIONS
- type: document
  path: data/pageBlocks/mainscreen.json
  label: Main Screen
- type: document
  path: data/pageBlocks/aboutme.json
  label: About me
- type: document
  path: data/pageBlocks/achievements.json
  label: Achievements
- type: document
  path: data/pageBlocks/courses.json
  label: Courses
- type: document
  path: data/pageBlocks/contacts.json
  label: Contacts
upload_dir: nzh
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  instant_preview_command: vuepress dev -p 8080 -h 0.0.0.0
