---
label: 'Theme config '
hide_body: true
fields:
- type: text
  name: site_name
  label: Site name
  description: Введите название сайта
- type: textarea
  name: site_description
  label: Site description
  description: Введите описание сайта
- type: textarea
  name: hero_title
  config:
    wysiwyg: true
    schema:
      format: html
  label: Заголовок главной страницы
  description: Введите заголовок для главной страницы
- type: textarea
  name: hero_subtitle
  config:
    wysiwyg: true
    schema:
      format: html
  label: Подзаголовок главной страницы
  description: 'Введите Подзаголовок для главной страницы '
- name: footer
  label: Footer text
  type: text
  hidden: false
  default: ''
- name: cloudinary_url
  type: text
  config:
    required: false
  label: Cloudinary URL
  hidden: true
  default: https://res.cloudinary.com/nzh
  description: Не редактировать
pages:
- data/theme.json
