---
label: 'Theme config '
hide_body: true
fields:
- type: text
  name: site_name
  label: Site name
- type: textarea
  name: site_description
  label: Site description
- name: key_words
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Key words
- name: cloudinary_url
  type: text
  config:
    required: false
  label: Cloudinary URL
  hidden: true
  default: https://res.cloudinary.com/nataliazharkova
  description: Не редактировать
