---
label: Main info
hide_body: true
fields:
- type: text
  name: site_name
  label: Site name
- type: textarea
  name: site_description
  label: Site description
- name: key_words
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Key words
- name: socials
  type: blocks
  label: Socials
  template_types:
  - social-item
  config:
    min: 
    max: 
- name: cloudinary_url
  type: text
  config:
    required: false
  label: Cloudinary URL
  hidden: true
  default: https://res.cloudinary.com/nataliazharkova
  description: Не редактировать
- name: address
  type: text
  config:
    required: false
  label: Address
- name: phone_number
  type: text
  config:
    required: false
  label: Phone number
- name: email
  type: text
  config:
    required: false
  label: Email
- name: header_title
  type: text
  config:
    required: false
  label: Header title
  description: For mobile and tablet only
- name: header_subtitle
  type: text
  config:
    required: false
  label: Header subtitle
  description: For mobile and tablet only
- name: mobile_menu_socials
  type: blocks
  label: Mobile menu socials
  template_types:
  - social-item
  config:
    min: 
    max: 
pages:
- data/main.json
